/**
 * Export Utilities
 * Functions for exporting charts and maps as PNG or PDF
 * Uses html2canvas for image generation and jsPDF for PDF creation
 */

/**
 * Export element as PNG image
 * @param {HTMLElement} element - DOM element to export
 * @param {string} filename - Output filename (without extension)
 * @param {Object} options - Export options
 * @returns {Promise<void>}
 */
export const exportAsPNG = async (element, filename = 'export', options = {}) => {
  const {
    backgroundColor = '#ffffff',
    scale = 2,
    width = null,
    height = null,
  } = options;

  try {
    // Dynamically import html2canvas
    const html2canvas = await importHtml2Canvas();

    const canvas = await html2canvas(element, {
      backgroundColor,
      scale,
      width,
      height,
      useCORS: true,
      allowTaint: true,
      logging: false,
    });

    // Convert canvas to blob
    canvas.toBlob((blob) => {
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${filename}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    });
  } catch (error) {
    console.error('Error exporting as PNG:', error);
    throw error;
  }
};

/**
 * Export element as PDF
 * @param {HTMLElement} element - DOM element to export
 * @param {string} filename - Output filename (without extension)
 * @param {Object} options - Export options
 * @returns {Promise<void>}
 */
export const exportAsPDF = async (element, filename = 'export', options = {}) => {
  const {
    orientation = 'portrait',
    format = 'a4',
    backgroundColor = '#ffffff',
    scale = 2,
  } = options;

  try {
    // Dynamically import libraries
    const [html2canvas, { jsPDF }] = await Promise.all([
      importHtml2Canvas(),
      importJsPDF(),
    ]);

    const canvas = await html2canvas(element, {
      backgroundColor,
      scale,
      useCORS: true,
      allowTaint: true,
      logging: false,
    });

    const imgData = canvas.toDataURL('image/png');

    // Create PDF
    const pdf = new jsPDF({
      orientation,
      unit: 'mm',
      format,
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();

    // Calculate dimensions to fit page
    const imgWidth = pageWidth - 20; // 10mm margin on each side
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let yPosition = 10;

    // If image is taller than page, scale to fit
    if (imgHeight > pageHeight - 20) {
      const scaledHeight = pageHeight - 20;
      const scaledWidth = (canvas.width * scaledHeight) / canvas.height;
      pdf.addImage(imgData, 'PNG', (pageWidth - scaledWidth) / 2, yPosition, scaledWidth, scaledHeight);
    } else {
      pdf.addImage(imgData, 'PNG', 10, yPosition, imgWidth, imgHeight);
    }

    // Add footer
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(
      `Generated by Touch of Terra Dashboard - ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      pageHeight - 5,
      { align: 'center' }
    );

    pdf.save(`${filename}.pdf`);
  } catch (error) {
    console.error('Error exporting as PDF:', error);
    throw error;
  }
};

/**
 * Export multiple elements as multi-page PDF
 * @param {Array<HTMLElement>} elements - Array of DOM elements
 * @param {string} filename - Output filename
 * @param {Object} options - Export options
 * @returns {Promise<void>}
 */
export const exportMultiPagePDF = async (elements, filename = 'dashboard-export', options = {}) => {
  const {
    orientation = 'portrait',
    format = 'a4',
    backgroundColor = '#ffffff',
    scale = 2,
    titles = [],
  } = options;

  try {
    const [html2canvas, { jsPDF }] = await Promise.all([
      importHtml2Canvas(),
      importJsPDF(),
    ]);

    const pdf = new jsPDF({
      orientation,
      unit: 'mm',
      format,
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();

    for (let i = 0; i < elements.length; i++) {
      if (i > 0) pdf.addPage();

      // Add title if provided
      if (titles[i]) {
        pdf.setFontSize(16);
        pdf.setTextColor(0, 0, 0);
        pdf.text(titles[i], pageWidth / 2, 15, { align: 'center' });
      }

      const canvas = await html2canvas(elements[i], {
        backgroundColor,
        scale,
        useCORS: true,
        allowTaint: true,
        logging: false,
      });

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = pageWidth - 20;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      const yPosition = titles[i] ? 25 : 10;

      if (imgHeight > pageHeight - yPosition - 10) {
        const scaledHeight = pageHeight - yPosition - 10;
        const scaledWidth = (canvas.width * scaledHeight) / canvas.height;
        pdf.addImage(imgData, 'PNG', (pageWidth - scaledWidth) / 2, yPosition, scaledWidth, scaledHeight);
      } else {
        pdf.addImage(imgData, 'PNG', 10, yPosition, imgWidth, imgHeight);
      }
    }

    // Add footer on last page
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(
      `Generated by Touch of Terra Dashboard - ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      pageHeight - 5,
      { align: 'center' }
    );

    pdf.save(`${filename}.pdf`);
  } catch (error) {
    console.error('Error exporting multi-page PDF:', error);
    throw error;
  }
};

/**
 * Dynamically import html2canvas
 * @returns {Promise<Function>}
 */
const importHtml2Canvas = async () => {
  try {
    const module = await import('html2canvas');
    return module.default;
  } catch (error) {
    console.error('Failed to load html2canvas. Please install: npm install html2canvas');
    throw new Error('html2canvas library not available');
  }
};

/**
 * Dynamically import jsPDF
 * @returns {Promise<Object>}
 */
const importJsPDF = async () => {
  try {
    return await import('jspdf');
  } catch (error) {
    console.error('Failed to load jsPDF. Please install: npm install jspdf');
    throw new Error('jsPDF library not available');
  }
};

/**
 * Prepare element for export (add styles, fix dimensions)
 * @param {HTMLElement} element - Element to prepare
 * @returns {Function} Cleanup function
 */
export const prepareForExport = (element) => {
  const originalStyles = {
    position: element.style.position,
    left: element.style.left,
    top: element.style.top,
  };

  // Temporarily adjust styles for better export
  element.style.position = 'relative';
  element.style.left = '0';
  element.style.top = '0';

  // Return cleanup function
  return () => {
    element.style.position = originalStyles.position;
    element.style.left = originalStyles.left;
    element.style.top = originalStyles.top;
  };
};

/**
 * Export dashboard data as JSON
 * @param {Object} data - Dashboard data to export
 * @param {string} filename - Output filename
 */
export const exportDataAsJSON = (data, filename = 'dashboard-data') => {
  const jsonStr = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Export dashboard data as CSV
 * @param {Array} data - Array of data objects
 * @param {string} filename - Output filename
 */
export const exportDataAsCSV = (data, filename = 'dashboard-data') => {
  if (!Array.isArray(data) || data.length === 0) {
    console.error('Data must be a non-empty array');
    return;
  }

  // Get headers from first object
  const headers = Object.keys(data[0]);
  const csvRows = [headers.join(',')];

  // Convert each object to CSV row
  data.forEach((row) => {
    const values = headers.map((header) => {
      const value = row[header] || '';
      return `"${String(value).replace(/"/g, '""')}"`;
    });
    csvRows.push(values.join(','));
  });

  const csvStr = csvRows.join('\n');
  const blob = new Blob([csvStr], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export default {
  exportAsPNG,
  exportAsPDF,
  exportMultiPagePDF,
  prepareForExport,
  exportDataAsJSON,
  exportDataAsCSV,
};
